<?php
function displaySide(){
    echo "<aside>" . PHP_EOL;
    echo "        <section>" . PHP_EOL;
    echo "            <h3>Nos 2 livres</h3>" . PHP_EOL;
    echo "            <a href=\"#\"><figure><img src=\"vue/img/aside/books.png\" alt=\"Livres\"></figure></a>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section class=\"youtube\">" . PHP_EOL;
    echo "            <h3>BA de notre \"Aventure sans frigo\"</h3>" . PHP_EOL;
    echo "            <!-- Start Youtube video integration -->" . PHP_EOL;
    echo "            <iframe src=\"https://videopress.com/embed/R47x8qzQ\" allowfullscreen></iframe>" . PHP_EOL;
    echo "            <script src=\"https://videopress.com/videopress-iframe.js\"></script>" . PHP_EOL;
    echo "            <!-- End Youtube video integration -->" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section>" . PHP_EOL;
    echo "            <h3>Slow journalism</h3>" . PHP_EOL;
    echo "            <a href=\"#\"><figure><img src=\"vue/img/aside/slow_journalism.jpg\" alt=\"Saladier remplis de légumes\"></figure></a>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section>" . PHP_EOL;
    echo "            <h3>Retrouvez la cabane anti-gaspi sur les réseaux sociaux</h3>" . PHP_EOL;
    echo "            <div class=\"social-links\">" . PHP_EOL;
    echo "                <a href=\"#\"><i class=\"fab fa-facebook-square\"></i></a>" . PHP_EOL;
    echo "                <a href=\"#\"><i class=\"fab fa-instagram\"></i></a>" . PHP_EOL;
    echo "                <a href=\"#\"><i class=\"fab fa-youtube-square\"></i></a>" . PHP_EOL;
    echo "            </div>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section>" . PHP_EOL;
    echo "            <h3>Pour me contacter</h3>" . PHP_EOL;
    echo "            <address><a href=\"mailto:mariecochard@mpluso.com\">mariecochard@mpluso.com</a></address>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section class=\"blogger-network\">" . PHP_EOL;
    echo "            <figure><h3><img src=\"vue/img/aside/zero_waste_logo.png\" alt=\"Logo Zero Waste Bloggers Network\"></h3></figure>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section class=\"copyright\">" . PHP_EOL;
    echo "            <h3>COPYRIGHT &copy; 2016 LACABANE-ANTIGASPI. DESIGNED BY MPLUSO</h3>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "    </aside>" . PHP_EOL;
    echo "</div>" . PHP_EOL;
    echo "</div>" . PHP_EOL;
}