<?php
function displayHomeContent(){
    echo "</header>" . PHP_EOL;
    echo "<div class=\"main-content\">" . PHP_EOL;
    echo "    <div class=\"articles\">" . PHP_EOL;
    echo "        <article class=\"article\">" . PHP_EOL;
    echo "            <figure><img src=\"vue/img/articles/article1.jpg\" alt=\"\"></figure>" . PHP_EOL;
    echo "            <div class=\"article-texts\">" . PHP_EOL;
    echo "                <h2 class=\"article-title\">Lire entre les vignes</h2>" . PHP_EOL;
    echo "                <div class=\"article-informations\">" . PHP_EOL;
    echo "                    <time datetime=\"2018-03-16\">16 mars 2018</time>" . PHP_EOL;
    echo "                    <a href=\"#\" class=\"article-informations-comments\">Laisser un commentaire</a>" . PHP_EOL;
    echo "                </div>" . PHP_EOL;
    echo "                <p>Le sauternes de La Clotte-Cazalis, à Barsac, est sincère, frais, vivant à l’image de celle qui le façonne amoureusement. Chez Marie-Pierre, pas de mécanique, pas de maquillage, pas d’artifice. On travaille à l’ancienne, en fonction des constellations, des cycles lunaires, avec le soutien des plantes et de Taropa, le cheval de trait.</p>" . PHP_EOL;
    echo "                <a href=\"#\">Lire la suite &rarr;</a>" . PHP_EOL;
    echo "            </div>" . PHP_EOL;
    echo "        </article>" . PHP_EOL;
    echo "        <article class=\"article\">" . PHP_EOL;
    echo "            <figure><img src=\"vue/img/articles/article2.jpg\" alt=\"\"></figure>" . PHP_EOL;
    echo "            <div class=\"article-texts\">" . PHP_EOL;
    echo "                <h2 class=\"article-title\">Petite cuisine pour avoir bonne mine &hellip;</h2>" . PHP_EOL;
    echo "                <div class=\"article-informations\">" . PHP_EOL;
    echo "                    <time datetime=\"2018-02-13\">13 février 2018</time>" . PHP_EOL;
    echo "                    <a href=\"#\" class=\"article-informations-comments\">4 commentaires</a>" . PHP_EOL;
    echo "                </div>" . PHP_EOL;
    echo "                <p>Il fait gris dehors et votre teint commence à prendre les couleurs du ciel ? Voici des petites recettes pour retrouver une peau de pêche en deux coups de cuillères à pot, et devinez quoi ? Les ingrédients pour réaliser la crème de la crème se trouvent juste là, dans vos placards de cuisine.</p>" . PHP_EOL;
    echo "                <a href=\"#\">Lire la suite &rarr;</a>" . PHP_EOL;
    echo "            </div>" . PHP_EOL;
    echo "        </article>" . PHP_EOL;
    echo "        <article class=\"article\">" . PHP_EOL;
    echo "            <figure><img src=\"vue/img/articles/article3.jpg\" alt=\"\"></figure>" . PHP_EOL;
    echo "            <div class=\"article-texts\">" . PHP_EOL;
    echo "                <h2 class=\"article-title\">Ciel ! J'ai mes lunes &hellip;</h2>" . PHP_EOL;
    echo "                <div class=\"article-informations\">" . PHP_EOL;
    echo "                    <time datetime=\"2018-02-05\">5 février 2018</time>" . PHP_EOL;
    echo "                    <a href=\"#\" class=\"article-informations-comments\">9 commentaires</a>" . PHP_EOL;
    echo "                </div>" . PHP_EOL;
    echo "                <p>Une fois n’est pas coutume, j’évoquerais au fil de ce nouveau billet nos lunes, nos coquelicots, nos isabelles, nos fleurs, nos bénéfices, nos ourses, nos culottes françaises… Si le sujet est resté longtemps tabou, forcé de constater que les fabuleux écrits de Miranda Gray (dont le fameux Lune rouge), suivi de près du mouvement « zéro déchet » ont fait évolué les mentalités… Accueillez donc avec honneur et légèreté votre féminin sacré.</p>" . PHP_EOL;
    echo "                <a href=\"#\">Lire la suite &rarr;</a>" . PHP_EOL;
    echo "            </div>" . PHP_EOL;
    echo "        </article>" . PHP_EOL;
    echo "        <a href=\"#\" class=\"btn\">Articles précédents</a>" . PHP_EOL;
    echo "    </div>" . PHP_EOL;
}