<?php
function displayFooter(){
    echo "<footer>" . PHP_EOL;
    echo "        <section class=\"news\">" . PHP_EOL;
    echo "            <h3>News</h3>" . PHP_EOL;
    echo "            <nav>" . PHP_EOL;
    echo "                <ul class=\"news-list-container\">" . PHP_EOL;
    echo "                    <li>" . PHP_EOL;
    echo "                        <a href=\"#\">LIRE ENTRE LES VIGNES</a>" . PHP_EOL;
    echo "                        <time datetime=\"2018-03-16\">16 mars 2018</time>" . PHP_EOL;
    echo "                    </li>" . PHP_EOL;
    echo "                    <li>" . PHP_EOL;
    echo "                        <a href=\"#\">PETITE CUISINE POUR AVOIR BONNE MINE …</a>" . PHP_EOL;
    echo "                        <time datetime=\"2018-02-13\">13 février 2018</time>" . PHP_EOL;
    echo "                    </li>" . PHP_EOL;
    echo "                    <li>" . PHP_EOL;
    echo "                        <a href=\"#\">CIEL ! J’AI MES LUNES …</a>" . PHP_EOL;
    echo "                        <time datetime=\"2018-02-05\">5 février 2018</time>" . PHP_EOL;
    echo "                    </li>" . PHP_EOL;
    echo "                    <li>" . PHP_EOL;
    echo "                        <a href=\"#\">RECETTES « BIOTÉ » À CONCOCTER EN CUISINE !</a>" . PHP_EOL;
    echo "                        <time datetime=\"2018-01-29\">29 janvier 2018</time>" . PHP_EOL;
    echo "                    </li>" . PHP_EOL;
    echo "                    <li>" . PHP_EOL;
    echo "                        <a href=\"#\">EMBALLAGES « ZÉRO-DÉCHET »</a>" . PHP_EOL;
    echo "                        <time datetime=\"2018-01-02\">2 janvier 2018</time>" . PHP_EOL;
    echo "                    </li>" . PHP_EOL;
    echo "                </ul>" . PHP_EOL;
    echo "            </nav>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section>" . PHP_EOL;
    echo "            <h3>Catégories</h3>" . PHP_EOL;
    echo "            <nav>" . PHP_EOL;
    echo "                <ul class=\"categories-list-container\">" . PHP_EOL;
    echo "                    <li><a href=\"#\">ÉCO VOYAGE</a></li>" . PHP_EOL;
    echo "                    <li><a href=\"#\">ENFANTS DES BOIS</a></li>" . PHP_EOL;
    echo "                    <li><a href=\"#\">FAIT MAISON</a></li>" . PHP_EOL;
    echo "                    <li><a href=\"#\">LOCAVORISME</a></li>" . PHP_EOL;
    echo "                    <li><a href=\"#\">PERMACULTURE</a></li>" . PHP_EOL;
    echo "                    <li><a href=\"#\">ZÉRO DÉCHETS</a></li>" . PHP_EOL;
    echo "                </ul>" . PHP_EOL;
    echo "            </nav>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "        <section>" . PHP_EOL;
    echo "            <h3>Mentions légales</h3>" . PHP_EOL;
    echo "            <p>Toute reproduction ou représentation totale ou partielle de ce site (textes et images) par quelque procédé que ce soit, sans l’autorisation expresse du propriétaire du site ou de ses représentants légaux est interdite et constituerait une contrefaçon sanctionnée par les articles L335-2 et suivants du Code de la propriété intellectuelle.</p>" . PHP_EOL;
    echo "        </section>" . PHP_EOL;
    echo "    </footer>" . PHP_EOL;
    echo "    <script" . PHP_EOL;
    echo "  src=\"https://code.jquery.com/jquery-3.3.1.slim.js\" integrity=\"sha256-fNXJFIlca05BIO2Y5zh1xrShK3ME+/lYZ0j+ChxX2DA=\" crossorigin=\"anonymous\"></script>" . PHP_EOL;
    echo "    <script src=\"vue/js/script.js\"></script>" . PHP_EOL;
    echo "</body>" . PHP_EOL;
    echo "</html>" . PHP_EOL;
}